## numpy의 np.random. randint vs rand/randn

In [5]:
import numpy as np

### random.randint 와 np.random.randint: 모두 (시작, n-1)사이의 랜덤숫자 1개 뽑아내기

In [6]:
np.random.randint(6) # 0 or 1 or ~ or 5 0부터 5까지 랜덤한 숫자 1개

5

In [7]:
np.random.randint(1, 20) # 1부터 19까지 랜덤숫자 1개

1

### np.random.rand(m, n): 0~1의 균일분포 표준정규분포 난수를 matrix array(m, n) 생성

In [9]:
np.random.rand(6)

array([0.85868519, 0.482928  , 0.77046599, 0.55806735, 0.5556504 ,
       0.44844686])

In [10]:
np.random.rand(3, 2)

array([[0.67853101, 0.91261452],
       [0.13383638, 0.98593526],
       [0.53658162, 0.54891457]])

### np.random.randn(m, n): 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array(m, n) 생성

In [12]:
np.random.randn(6)

array([-1.60904294, -1.44775654, -0.51251945,  0.55278743,  1.16012706,
       -0.64197999])

In [13]:
np.random.randn(3, 2)

array([[-0.82345261, -0.99082112],
       [-0.89482928,  0.585453  ],
       [ 0.39160042,  0.2839424 ]])