## numpy의 np.random. randint vs rand/randn

In [14]:
import numpy as np

### random.randint 와 np.random.randint: 모두 (시작, n-1)사이의 랜덤숫자 1개 뽑아내기

In [15]:
np.random.randint(6) # 0 or 1 or ~ or 5 0부터 5까지 랜덤한 숫자 1개

0

In [16]:
np.random.randint(1, 20) # 1부터 19까지 랜덤숫자 1개

4

### np.random.rand(m, n): 0~1의 균일분포 표준정규분포 난수를 matrix array(m, n) 생성

In [17]:
np.random.rand(6)

array([0.13534669, 0.71963895, 0.7098752 , 0.2419438 , 0.43946478,
       0.07232738])

In [18]:
np.random.rand(3, 2)

array([[0.17127021, 0.84515513],
       [0.97746306, 0.91054945],
       [0.27888092, 0.44155948]])

### np.random.randn(m, n): 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array(m, n) 생성

In [19]:
np.random.randn(6)

array([ 1.3382555 , -0.50555816,  0.6951055 , -1.20642928, -0.66456533,
        1.2107802 ])

In [20]:
np.random.randn(3, 2)

array([[ 1.17339907, -1.28503315],
       [ 0.059875  ,  0.14217066],
       [-0.6598699 ,  1.3190116 ]])