## numpy의 np.random. randint vs rand/randn

In [1]:
import numpy as np

### random.randint 와 np.random.randint: 모두 (시작, n-1)사이의 랜덤숫자 1개 뽑아내기

In [2]:
np.random.randint(6) # 0 or 1 or ~ or 5 0부터 5까지 랜덤한 숫자 1개

1

In [3]:
np.random.randint(1, 20) # 1부터 19까지 랜덤숫자 1개

18

### np.random.rand(m, n): 0~1의 균일분포 표준정규분포 난수를 matrix array(m, n) 생성

In [4]:
np.random.rand(6)

array([0.84418492, 0.08592281, 0.44820759, 0.79101536, 0.59130448,
       0.93585538])

In [5]:
np.random.rand(3, 2)

array([[0.62496028, 0.80464104],
       [0.3374127 , 0.6952928 ],
       [0.91153751, 0.36006752]])

### np.random.randn(m, n): 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array(m, n) 생성

In [6]:
np.random.randn(6)

array([0.0123805 , 1.35617484, 0.63135042, 0.05444142, 0.95655533,
       0.04472164])

In [7]:
np.random.randn(3, 2)

array([[-0.08566585, -1.1067516 ],
       [ 0.73068895, -0.831362  ],
       [ 0.19359549,  0.79427797]])